---

{{ if $.Values.HttpRouteEnable }}

apiVersion: "gateway.networking.k8s.io/v1"
kind: "HTTPRoute"

metadata:
  name: "dss"
  namespace: "{{ $.Release.Namespace }}"

spec:

  parentRefs:
  - name: "traefik-gateway"
    namespace: "traefik"

  hostnames:
  - "dss.local"

  rules:
  - backendRefs:
    - name: "dss"
      port: 80

{{ end }}

