---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: dss
  namespace: {{ $.Release.Namespace }}
  labels:
    app: dss

spec:
  selector:
    matchLabels:
      app: dss
  template:
    metadata:
      name: dss
      labels:
        app: dss

    spec:

      volumes:
        - name: dss
          hostPath:
            path: /opt/dss/
            type: DirectoryOrCreate

      containers:

        - name: dss
          image: "{{ $.Values.ImageNameGithubDss }}:{{ $.Values.ImageTagGithubDss }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: downloads
              mountPath: /dss/
          ports:
            - containerPort: 80


